// ============================================================
//  mots.js – Paires de mots pour le jeu Undercover
//  Format : [mot_civil, mot_undercover]
//  Ajoutez facilement de nouvelles catégories ou paires !
// ============================================================

const words = {
  anime: [
    ["Naruto","Sasuke"],
["Naruto","Kakashi"],
["Naruto","Sakura"],
["Naruto","Hinata"],
["Naruto","Gaara"],
["Naruto","Shikamaru"],
["Naruto","Neji"],
["Naruto","Jiraiya"],
["Naruto","Minato"],
["Naruto","Obito"],
["Sasuke","Itachi"],
["Sasuke","Kakashi"],
["Sasuke","Madara"],
["Sakura","Ino"],
["Sakura","Tsunade"],
["Kakashi","Guy"],
["Kakashi","Obito"],
["Kakashi","Yamato"],
["Shikamaru","Choji"],
["Shikamaru","Temari"],
["Hinata","Neji"],
["Gaara","Kankuro"],
["Gaara","Temari"],
["Itachi","Kisame"],
["Jiraiya","Tsunade"],
["Jiraiya","Orochimaru"],
["Minato","Kushina"],
["Madara","Hashirama"],
["Obito","Rin"],
["Pain","Konan"],

["Luffy","Zoro"],
["Luffy","Sanji"],
["Luffy","Nami"],
["Luffy","Usopp"],
["Luffy","Chopper"],
["Luffy","Robin"],
["Luffy","Franky"],
["Luffy","Brook"],
["Luffy","Jinbe"],
["Zoro","Sanji"],
["Zoro","Mihawk"],
["Sanji","Nami"],
["Sanji","Pudding"],
["Nami","Robin"],
["Usopp","Yasopp"],
["Chopper","Robin"],
["Chopper","Brook"],
["Franky","Brook"],
["Franky","Robin"],
["Ace","Luffy"],
["Ace","Sabo"],
["Sabo","Luffy"],
["Shanks","Luffy"],
["Shanks","Buggy"],
["Law","Luffy"],
["Law","Kid"],
["Kid","Killer"],
["Kaido","Big Mom"],
["Whitebeard","Marco"],
["Blackbeard","Shanks"],

["Eren","Mikasa"],
["Eren","Armin"],
["Eren","Levi"],
["Eren","Reiner"],
["Mikasa","Levi"],
["Mikasa","Armin"],
["Armin","Annie"],
["Levi","Erwin"],
["Levi","Hange"],
["Erwin","Hange"],
["Reiner","Bertholdt"],
["Reiner","Annie"],
["Jean","Connie"],
["Jean","Sasha"],
["Sasha","Connie"],
["Historia","Ymir"],
["Zeke","Eren"],
["Zeke","Levi"],
["Hange","Moblit"],

["Tanjiro","Nezuko"],
["Tanjiro","Zenitsu"],
["Tanjiro","Inosuke"],
["Tanjiro","Giyu"],
["Nezuko","Zenitsu"],
["Zenitsu","Inosuke"],
["Inosuke","Aoi"],
["Giyu","Shinobu"],
["Shinobu","Kanae"],
["Shinobu","Kanao"],
["Kanao","Tanjiro"],
["Rengoku","Tanjiro"],
["Rengoku","Tengen"],
["Tengen","Mitsuri"],
["Mitsuri","Obanai"],
["Gyomei","Sanemi"],
["Sanemi","Genya"],
["Akaza","Rengoku"],
["Muzan","Akaza"],

["Goku","Vegeta"],
["Goku","Gohan"],
["Goku","Krillin"],
["Goku","Piccolo"],
["Goku","Frieza"],
["Vegeta","Bulma"],
["Vegeta","Trunks"],
["Gohan","Piccolo"],
["Gohan","Videl"],
["Piccolo","Gohan"],
["Krillin","Android 18"],
["Trunks","Goten"],
["Goten","Trunks"],
["Frieza","Cell"],
["Cell","Gohan"],
["Beerus","Whis"],
["Jiren","Goku"],
["Broly","Goku"],
["Broly","Vegeta"],

["Gon","Killua"],
["Gon","Hisoka"],
["Gon","Kurapika"],
["Killua","Illumi"],
["Killua","Hisoka"],
["Kurapika","Leorio"],
["Kurapika","Chrollo"],
["Leorio","Gon"],
["Hisoka","Chrollo"],
["Chrollo","Feitan"],
["Meruem","Komugi"],
["Meruem","Neferpitou"],
["Pitou","Gon"],
["Knuckle","Shoot"],
["Morel","Knov"],

["Yuji","Megumi"],
["Yuji","Nobara"],
["Yuji","Gojo"],
["Megumi","Nobara"],
["Megumi","Gojo"],
["Gojo","Geto"],
["Gojo","Toji"],
["Geto","Toji"],
["Nobara","Maki"],
["Maki","Mai"],
["Yuta","Rika"],
["Yuta","Gojo"],
["Nanami","Yuji"],
["Choso","Yuji"],
["Sukuna","Yuji"],

["Denji","Power"],
["Denji","Aki"],
["Denji","Makima"],
["Power","Aki(chainsaw man)"],
["Aki(chainsaw man)","Himeno"],
["Makima","Denji"],
["Kishibe","Quanxi"],
["Quanxi","Makima"],
["Beam","Denji"],

["Saitama","Genos"],
["Saitama","King"],
["Genos","Dr Kuseno"],
["Fubuki","Tatsumaki"],
["Tatsumaki","Saitama"],
["Bang","Bomb"],

["Asta","Yuno"],
["Asta","Noelle"],
["Yuno","Noelle"],
["Yami","Asta"],
["Yami","Finral"],
["Noelle","Mimosa"],
["Luck","Magna"],

["Izuku","Bakugo"],
["Izuku","Todoroki"],
["Izuku","All Might"],
["Bakugo","Kirishima"],
["Todoroki","Endeavor"],
["Ochaco","Izuku"],
["Ochaco","Tsuyu"],
["All Might","Endeavor"],
["Shigaraki","All For One"],
["Dabi","Shigaraki"],

["Rimuru","Benimaru"],
["Rimuru","Shion"],
["Rimuru","Shuna"],
["Benimaru","Shuna"],
["Shion","Shuna"],

["Kirito","Asuna"],
["Kirito","Sinon"],
["Asuna","Yuuki"],
["Sinon","Leafa"],

["Ainz","Albedo"],
["Ainz","Demiurge"],
["Albedo","Shalltear"],
["Shalltear","Cocytus"],

["Light","L"],
["Light","Misa"],
["L","Near"],


["Edward","Alphonse"],
["Edward","Winry"],
["Roy Mustang","Riza Hawkeye"],
["Scar","Edward"],

["Natsu","Lucy"],
["Natsu","Gray"],
["Lucy","Erza"],
["Gray","Juvia"],
["Erza","Jellal"],

["Meliodas","Ban"],
["Meliodas","Elizabeth"],
["Ban","Elaine"],
["King","Diane"],

["Senku","Chrome"],
["Senku","Gen"],
["Kohaku","Ruri"],

["Mob","Reigen"],
["Mob","Ritsu"],
["Reigen","Dimple"],
],

  films: [
    ["Harry Potter","Ron Weasley"],
["Harry Potter","Hermione Granger"],
["Harry Potter","Draco Malfoy"],
["Harry Potter","Voldemort"],
["Harry Potter","Dumbledore"],
["Ron Weasley","Hermione Granger"],
["Ron Weasley","Ginny Weasley"],
["Hermione Granger","Ginny Weasley"],
["Draco Malfoy","Lucius Malfoy"],
["Draco Malfoy","Rogue"],
["Rogue","Dumbledore"],
["Hagrid","Harry Potter"],
["Hagrid","Dumbledore"],
["Sirius Black","Harry Potter"],
["Sirius Black","Remus Lupin"],

["Luke Skywalker","Leia"],
["Luke Skywalker","Han Solo"],
["Luke Skywalker","Dark Vader"],
["Leia","Han Solo"],
["Han Solo","Chewbacca"],
["Dark Vader","Palpatine"],
["Obi-Wan Kenobi","Anakin Skywalker"],
["Obi-Wan Kenobi","Yoda"],
["Yoda","Windu"],


["Iron Man","Captain America"],
["Iron Man","Spider-Man"],
["Iron Man","War Machine"],
["Captain America","Bucky"],
["Captain America","Falcon"],
["Thor","Loki"],
["Thor","Hulk"],
["Hulk","Black Widow"],
["Black Widow","Hawkeye"],
["Hawkeye","Kate Bishop"],
["Doctor Strange","Wong"],
["Doctor Strange","Scarlet Witch"],
["Scarlet Witch","Vision"],
["Star-Lord","Gamora"],
["Star-Lord","Rocket"],
["Gamora","Nebula"],
["Rocket","Groot"],
["Thanos","Gamora"],
["Thanos","Iron Man"],
["Ant-Man","Wasp"],

["Batman","Robin"],
["Batman","Joker"],
["Batman","Catwoman"],
["Joker","Harley Quinn"],
["Harley Quinn","Poison Ivy"],
["Superman","Lois Lane"],
["Superman","Lex Luthor"],
["Flash","Cyborg"],
["Flash","Reverse Flash"],
["Green Lantern","Sinestro"],
["Shazam","Black Adam"],

["Frodon","Sam"],
["Frodon","Gandalf"],
["Frodon","Aragorn"],
["Sam","Gollum"],
["Aragorn","Legolas"],
["Gandalf","Saruman"],


["Jack Sparrow","Will Turner"],
["Jack Sparrow","Elizabeth Swann"],
["Jack Sparrow","Barbossa"],
["Will Turner","Elizabeth Swann"],
["Davy Jones","Jack Sparrow"],

["Neo","Morpheus"],
["Neo","Trinity"],
["Morpheus","Trinity"],
["Agent Smith","Neo"],


["Shrek","L'Âne (Shrek)"],
["Shrek","Fiona"],
["L'Âne (Shrek)","Dragon"],

["Simba","Nala"],
["Simba","Mufasa"],
["Scar","Simba"],
["Timon","Pumbaa"],

["Woody","Buzz"],
["Woody","Jessie"],
["Buzz","Zurg"],

["Harold ","Krokmou"],
["Harold ","Astrid"],
["Stoick","Harold "],

["Gru","Dr Nefario"],
["Gru","Lucy Wilde"],
["Gru","Vector"],
["Margo","Agnes"],

["Sherlock Holmes","John Watson"],
["Sherlock Holmes","Moriarty"],
["John Watson","Mary Watson"],


["Wolverine","Professor X"],
["Wolverine","Jean Grey"],
["Professor X","Magneto"],
["Magneto","Mystique"],


["Sarah Connor","John Connor"],
["Sarah Connor","Kyle Reese"],
["Terminator","John Connor"],
  ],

  jeuxvideo: [
    ["Mario","Luigi"],
["Mario","Peach"],
["Mario","Bowser"],
["Luigi","Peach"],
["Luigi","Daisy"],
["Peach","Daisy"],
["Bowser","Bowser Jr"],
["Yoshi","Mario"],
["Yoshi","Birdo"],
["Toad","Toadette"],
["Wario","Waluigi"],
["Donkey Kong","Diddy Kong"],
["Donkey Kong","Cranky Kong"],
["Diddy Kong","Dixie Kong"],

["Link","Zelda"],
["Link","Ganondorf"],
["Zelda","Impa"],
["Ganondorf","Zant"],
["Midna","Link"],
["Epona","Link"],
["Sheik","Zelda"],

["Pikachu","Ash"],
["Pikachu","Evoli"],
["Evoli","Mentali"],
["Evoli","Noctali"],
["Salamèche","Dracaufeu"],
["Carapuce","Tortank"],
["Bulbizarre","Florizarre"],
["Mewtwo","Mew"],
["Lucario","Pikachu"],
["Sacha","Ondine"],
["Sacha","Pierre"],

["Kratos","Atreus"],
["Kratos","Zeus"],
["Atreus","Freya"],
["Baldur","Freya"],
["Thor","Odin"],
["Kratos","Freya"],

["Master Chief","Cortana"],
["Master Chief","Arbiter"],
["Cortana","Halsey"],
["Arbiter","Thel 'Vadam"],

["Geralt","Ciri"],
["Geralt","Yennefer"],
["Geralt","Triss"],
["Ciri","Yennefer"],
["Yennefer","Triss"],
["Geralt","Dandelion"],

["Lara Croft","Natla"],
["Lara Croft","Zip"],
["Lara Croft","Winston"],

["Nathan Drake","Elena Fisher"],
["Nathan Drake","Sully"],
["Sully","Elena Fisher"],
["Nathan Drake","Sam Drake"],

["Joel","Ellie"],
["Joel","Tess"],
["Ellie","Dina"],
["Abby","Ellie"],
["Abby","Owen"],

["Cloud","Tifa"],
["Cloud","Aerith"],
["Cloud","Sephiroth"],
["Tifa","Barret"],
["Aerith","Zack"],
["Sephiroth","Genesis"],
["Barret","Marlene"],

["Sonic","Tails"],
["Sonic","Knuckles"],
["Sonic","Shadow"],
["Tails","Knuckles"],
["Shadow","Rouge"],
["Amy","Sonic"],

["Ryu","Ken"],
["Ryu","Chun-Li"],
["Ken","Chun-Li"],
["Guile","Chun-Li"],
["Bison","Vega"],

["Scorpion","Sub-Zero"],
["Scorpion","Raiden"],
["Sub-Zero","Noob Saibot"],
["Raiden","Liu Kang"],
["Kitana","Mileena"],
["Johnny Cage","Sonya Blade"],

["Steve","Alex"],
["Steve","Enderman"],
["Steve","Creeper"],
["Alex","Zombie"],
["Enderman","Ender Dragon"],

["CJ","Big Smoke"],
["CJ","Ryder"],
["CJ","Sweet"],
["Big Smoke","Ryder"],

["Arthur Morgan","Dutch"],
["Arthur Morgan","John Marston"],
["John Marston","Abigail"],
["Dutch","Micah"],
["Sadie Adler","Arthur Morgan"],

["Ezio","Altair"],
["Ezio","Leonardo"],
["Altair","Malik"],
["Connor","Haytham"],
["Edward Kenway","Blackbeard"],
["Bayek","Aya"],

["Shepard","Garrus"],
["Shepard","Liara"],
["Garrus","Tali"],
["Liara","Tali"],
["Shepard","Wrex"],

["Tracer","Winston"],
["Tracer","Reaper"],
["Reaper","Soldier 76"],
["Mercy","Genji"],
["Genji","Hanzo"],
["D.Va","Lucio"],

["Mario","Sonic"],
["Link","Cloud"],
["Pikachu","Kirby"],
["Samus","Ridley"],
["Fox","Falco"],
["Ness","Lucas"],

["Aloy","Sylens"],
["Aloy","Rost"],
["Aloy","Erend"],

["Jill Valentine","Chris Redfield"],
["Jill Valentine","Wesker"],
["Leon Kennedy","Ada Wong"],
["Leon Kennedy","Claire Redfield"],
["Chris Redfield","Claire Redfield"],
["Nemesis","Jill Valentine"],

["Ellie","Joel"],
["Ellie","Dina"],
["Ellie","Abby"],
["Joel","Tommy"],

["Sora","Riku"],
["Sora","Kairi"],
["Riku","Kairi"],
["Sora","Mickey"],

["Kirby","Meta Knight"],
["Kirby","King Dedede"],
["Meta Knight","King Dedede"],

["Gordon Freeman","Alyx Vance"],
["Gordon Freeman","G-Man"],
["Alyx Vance","Eli Vance"],

["Agent 47","Diana Burnwood"],
["Agent 47","Lucas Grey"],

["Sam Fisher","Grim"],
["Sam Fisher","Kestrel"],

["Marcus Fenix","Dom Santiago"],
["Marcus Fenix","Baird"],
["Dom Santiago","Maria"],

["Jin Kazama","Kazuya Mishima"],
["Jin Kazama","Hwoarang"],
["Kazuya Mishima","Heihachi Mishima"],
["Ling Xiaoyu","Jin Kazama"],

["Spyro","Sparx"],
["Spyro","Hunter"],

["Crash Bandicoot","Coco Bandicoot"],
["Crash Bandicoot","Dr Neo Cortex"],
["Coco Bandicoot","Crunch"],

["Shovel Knight","Shield Knight"],
["Shovel Knight","Black Knight"],

["Cuphead","Mugman"],
["Cuphead","The Devil"],

["Sans","Papyrus"],
["Sans","Frisk"],
["Papyrus","Undyne"],

["Chun-Li","Cammy"],
["Ryu","Akuma"],
["Ken","Akuma"],

["Bayonetta","Jeanne"],
["Bayonetta","Luka"],

["Doomguy","Demon"],
["Doomguy","Samuel Hayden"],

["Isaac","Guppy"],
["Isaac","Mom"],

["Vault Boy","Piper"],
["Vault Boy","Preston Garvey"],

["Trevor","Michael"],
["Trevor","Franklin"],
["Michael","Franklin"],
  ],

  general: [
   ["Chien","Chat"],
["Chien","Loup"],
["Chat","Tigre"],
["Chat","Panthère"],
["Lion","Tigre"],
["Lion","Guépard"],
["Souris","Rat"],
["Cheval","Âne"],
["Cheval","Poney"],
["Vache","Taureau"],
["Cochon","Sanglier"],
["Mouton","Chèvre"],
["Poulet","Dinde"],
["Canard","Oie"],
["Aigle","Faucon"],
["Requin","Dauphin"],
["Requin","Orque"],
["Dauphin","Baleine"],
["Grenouille","Crapaud"],
["Fourmi","Abeille"],
["Abeille","Guêpe"],
["Araignée","Scorpion"],
["Papillon","Mite"],
["Escargot","Limace"],

["Voiture","Camion"],
["Voiture","Moto"],
["Moto","Scooter"],
["Bus","Tramway"],
["Train","Métro"],
["Avion","Hélicoptère"],
["Bateau","Voilier"],
["Fusée","Navette spatiale"],
["Vélo","Trottinette"],
["Camion","Tracteur"],

["Pomme","Poire"],
["Pomme","Cerise"],
["Banane","Mangue"],
["Orange","Clémentine"],
["Citron","Lime"],
["Fraise","Framboise"],
["Raisin","Prune"],
["Pastèque","Melon"],
["Tomate","Concombre"],
["Carotte","Navet"],
["Brocoli","Chou-fleur"],
["Oignon","Ail"],
["Pain","Baguette"],
["Riz","Pâtes"],
["Poulet","Dinde"],
["Bœuf","Veau"],
["Saumon","Thon"],
["Lait","Yaourt"],
["Fromage","Beurre"],

["Table","Chaise"],
["Table","Bureau"],
["Chaise","Tabouret"],
["Lit","Matelas"],
["Armoire","Commode"],
["Canapé","Fauteuil"],
["Lampe","Ampoule"],
["Rideau","Volet"],
["Tapis","Moquette"],
["Télévision","Télécommande"],
["Ordinateur","Clavier"],
["Ordinateur","Souris"],
["Téléphone","Chargeur"],
["Réfrigérateur","Congélateur"],
["Four","Micro-ondes"],
["Lave-linge","Sèche-linge"],

["Crayon","Stylo"],
["Crayon","Gomme"],
["Stylo","Feutre"],
["Cahier","Classeur"],
["Livre","Magazine"],
["Règle","Équerre"],
["Sac","Cartable"],
["Feuille","Papier"],
["Colle","Ciseaux"],

["Soleil","Lune"],
["Soleil","Étoile"],
["Lune","Planète"],
["Terre","Mars"],
["Mars","Jupiter"],
["Jupiter","Saturne"],
["Saturne","Uranus"],
["Uranus","Neptune"],
["Galaxie","Univers"],
["Comète","Astéroïde"],

["Mer","Océan"],
["Rivière","Fleuve"],
["Montagne","Colline"],
["Forêt","Jungle"],
["Désert","Savane"],
["Plage","Côte"],
["Île","Archipel"],
["Vallée","Canyon"],

["Football","Rugby"],
["Football","Handball"],
["Basket","Volley"],
["Tennis","Badminton"],
["Natation","Plongée"],
["Course","Marathon"],
["Boxe","Kickboxing"],
["Ski","Snowboard"],
["Golf","Mini-golf"],

["Guitare","Basse"],
["Guitare","Ukulélé"],
["Piano","Clavier"],
["Batterie","Tambour"],
["Violon","Alto"],
["Trompette","Saxophone"],
["Flûte","Clarinette"],
["Micro","Enceinte"],

["Docteur","Infirmier"],
["Docteur","Chirurgien"],
["Professeur","Élève"],
["Policier","Gendarme"],
["Pompier","Secouriste"],
["Cuisinier","Serveur"],
["Pilote","Copilote"],
["Juge","Avocat"],
["Architecte","Ingénieur"],
["Peintre","Sculpteur"],

["Maison","Appartement"],
["Maison","Villa"],
["Appartement","Studio"],
["Jardin","Terrasse"],
["Cuisine","Salon"],
["Salle de bain","Toilettes"],
["Garage","Cave"],

["Hiver","Automne"],
["Hiver","Printemps"],
["Été","Printemps"],
["Jour","Nuit"],
["Matin","Soir"],
["Vent","Pluie"],
["Neige","Glace"],
["Orage","Tonnerre"],

["Bonbon","Chocolat"],
["Gâteau","Tarte"],
["Pizza","Burger"],
["Sandwich","Wrap"],
["Soupe","Bouillon"],
["Café","Thé"],
["Jus","Soda"],
["Eau","Limonade"],

["Roi","Reine"],
["Prince","Princesse"],
["Chevalier","Samouraï"],
["Magicien","Sorcier"],
["Vampire","Loup-garou"],
["Fantôme","Esprit"],
["Alien","Robot"],
["Pirate","Corsaire"],

["Clé","Serrure"],
["Carte","Plan"],
["Montre","Horloge"],
["Bague","Bracelet"],
["Chaussure","Botte"],
["Pantalon","Short"],
["T-shirt","Pull"],
["Manteau","Veste"],

["Film","Série"],
["Film","Documentaire"],
["Musique","Chanson"],
["Jeu vidéo","Console"],
["Livre","Roman"],
["Peinture","Dessin"],

["Argent","Or"],
["Argent","Billet"],
["Carte bancaire","Portefeuille"],
["Banque","Coffre"],

["Ville","Village"],
["Ville","Capitale"],
["Pays","Continent"],
["Route","Autoroute"],
["Pont","Tunnel"],
],

  sport: [
    ["Football", "Rugby"],
    ["Tennis", "Badminton"],
    ["Natation", "Plongée"],
    ["Boxe", "Karaté"],
    ["Basketball", "Handball"],
    ["Cyclisme", "Triathlon"],
    ["Golf", "Croquet"],
    ["Ski", "Snowboard"],
    ["Judo", "Lutte"],
    ["Escalade", "Alpinisme"]
  ],

  nourriture: [
    ["Sushi", "Maki"],
    ["Burger", "Hot-dog"],
    ["Lasagnes", "Cannelloni"],
    ["Croissant", "Pain au chocolat"],
    ["Ramen", "Pho"],
    ["Tiramisu", "Panna cotta"],
    ["Tacos", "Burrito"],
    ["Quiche", "Tarte salée"],
    ["Fondue", "Raclette"],
    ["Macaron", "Éclair"]
  ]
};

// Export pour Node.js (bot Discord)
if (typeof module !== "undefined") {
  module.exports = { words };
}
